# Generated by Django 5.1.4 on 2024-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('rain', models.FloatField()),
                ('snowfall', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
