# Generated by Django 5.1.4 on 2024-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_weather_wind_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='precipitation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='snowfall',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
